name: biof085
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy
  - sympy
  - pandas
  - scipy
  - seaborn
  - jupyterlab
  - jupyter
  - spyder
  - rise
  - jupytext
  - openpyxl

